FROM openjdk:11-slim as build

#maintainer
MAINTAINER vish.com

#jar copy
COPY target/accounts-0.0.1-SNAPSHOT.jar accounts-0.0.1-SNAPSHOT.jar

#execute and start app
ENTRYPOINT ["java", "-jar", "-Dnetwork.sql.host=${sqlserver}", "-Dnetwork.sql.host.port=${sqlport}", "/accounts-0.0.1-SNAPSHOT.jar"]