version: "3.8"

services:
  accounts:
    image: bankapp/accounts:latest
    mem_limit: 700m
    ports:
      - "18080:8080"
    environment:
      - sqlserver=mysqldb
      - sqlport=3306
      - SPRING_ACTIVE_PROFILES=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://bankappconfigserver:8071
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/
    # depends_on:
    #   - "mysqldb"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 120s
        max_attempts: 3
    networks:
      - bankapp-network

  loans:
    image: bankapp/loans:latest
    mem_limit: 700m
    environment:
      - sqlserver=mysqldb
      - sqlport=3306
      - SPRING_ACTIVE_PROFILES=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://bankappconfigserver:8071
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/
    ports:
      - "18090:8090"
    # depends_on:
    #   - "mysqldb"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 120s
        max_attempts: 3
    networks:
      - bankapp-network

  cards:
    image: bankapp/cards:latest
    mem_limit: 700m
    environment:
      - sqlserver=mysqldb
      - sqlport=3306
      - SPRING_ACTIVE_PROFILES=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://bankappconfigserver:8071
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/
    ports:
      - "18060:8060"
    # depends_on:
    #   - "mysqldb"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 120s
        max_attempts: 3
    networks:
      - bankapp-network

networks:
  bankapp-network:
    driver: bridge