version: "3.8"

services:
  mysqldb:
    image: mysql/mysql-server:8.0.20
    container_name: mysqldb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "18000:3306"
    volumes:
    - //d/dockeritems/mysqlvm:/var/lib/mysql
    - ./data.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: microservices_db
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword
    networks:
      - bankapp-network

  accounts:
    image: bankapp/accounts:latest
    mem_limit: 700m
    ports:
      - "18080:8080"
    environment:
      sqlserver: mysqldb
      sqlport: 3306
    depends_on:
      - "mysqldb"
    networks:
      - bankapp-network

  loans:
    image: bankapp/loans:latest
    mem_limit: 700m
    environment:
      sqlserver: mysqldb
      sqlport: 3306
    ports:
      - "18090:8090"
    depends_on:
      - "mysqldb"
    networks:
      - bankapp-network

  cards:
    image: bankapp/cards:latest
    mem_limit: 700m
    environment:
      sqlserver: mysqldb
      sqlport: 3306
    ports:
      - "18070:8070"
    networks:
      - bankapp-network
    depends_on:
      - "mysqldb"

networks:
  bankapp-network:
    driver: bridge