version: "3.8"

services:
  eurekaserver:
    image: bankapp/eurekaserver:latest
    mem_limit: 300m
    ports:
      - "18070:8070"
#    depends_on:
#      - "bankappconfigserver"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://bankappconfigserver:8071
    deploy:
      restart_policy:
        condition: on-failure
        delay: 120s
        max_attempts: 3  
    networks:
      - bankapp-network

  accounts:
    image: bankapp/accounts:latest
    mem_limit: 700m
    ports:
      - "18080:8080"
    environment:
      - sqlserver=mysqldb
      - sqlport=3306
      - SPRING_ACTIVE_PROFILES=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://bankappconfigserver:8071
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/
    depends_on:
      - "eurekaserver"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 120s
        max_attempts: 3
    networks:
      - bankapp-network

  loans:
    image: bankapp/loans:latest
    mem_limit: 700m
    environment:
      - sqlserver=mysqldb
      - sqlport=3306
      - SPRING_ACTIVE_PROFILES=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://bankappconfigserver:8071
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/
    ports:
      - "18090:8090"
    depends_on:
      - "eurekaserver"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 120s
        max_attempts: 3
    networks:
      - bankapp-network

  cards:
    image: bankapp/cards:latest
    mem_limit: 700m
    environment:
      - sqlserver=mysqldb
      - sqlport=3306
      - SPRING_ACTIVE_PROFILES=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://bankappconfigserver:8071
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/
    ports:
      - "18060:8060"
    depends_on:
      - "eurekaserver"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 120s
        max_attempts: 3
    networks:
      - bankapp-network


  gatewayserver:
    image: bankapp/gatewayserver:latest
    mem_limit: 700m
    ports:
      - "18072:8072"
    environment:
      - SPRING_ACTIVE_PROFILES=default
      - SPRING_CONFIG_IMPORT=optional:configserver:http://bankappconfigserver:8071
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/
    depends_on:
      - "eurekaserver"
      - "accounts"
      - "cards"
      - "loans"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 120s
        max_attempts: 3
    networks:
      - bankapp-network
networks:
  bankapp-network:
    driver: bridge