version: "3.8"

services:
  bankappconfigserver:
    image: bankapp/configserver:latest
    mem_limit: 300m
    ports:
      - "18071:8071"
    networks:
      - bankapp-network

  mysqldb:
    image: mysql/mysql-server:8.0.20
    container_name: mysqldb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "18000:3306"
    volumes:
    - //d/dockeritems/mysqlvm:/var/lib/mysql
    - ./data.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: microservices_db
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword
    networks:
      - bankapp-network 

networks:
  bankapp-network:
    driver: bridge