FROM openjdk:11-slim as build

#maintainer
MAINTAINER vish.com

#jar copy
COPY target/loans-0.0.1-SNAPSHOT.jar loans-0.0.1-SNAPSHOT.jar

#execute and start app
ENTRYPOINT ["java", "-jar", "-Dnetwork.sql.host=${sqlserver}", "-Dnetwork.sql.host.port=${sqlport}",  "/loans-0.0.1-SNAPSHOT.jar"]