deploymentName: gatewayserver-deployment
deploymentLabel: gatewayserver

replicaCount: 1

image:
  repository: vishvanaths/gatewayserver
  tag: latest

containerPort: 8072

service:
  type: LoadBalancer
  port: 8072
  targetPort: 8072

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true