FROM openjdk:11-slim as build

#maintainer
MAINTAINER vish.com

#jar copy
COPY target/gatewayserver-0.0.1-SNAPSHOT.jar gatewayserver-0.0.1-SNAPSHOT.jar

#execute and start app
ENTRYPOINT ["java", "-jar", "/gatewayserver-0.0.1-SNAPSHOT.jar"]