FROM openjdk:11-slim as build

#maintainer
MAINTAINER vish.com

#jar copy
COPY target/configserver-0.0.1-SNAPSHOT.jar configserver-0.0.1-SNAPSHOT.jar

#execute and start app
ENTRYPOINT ["java", "-jar", "/configserver-0.0.1-SNAPSHOT.jar"]