deploymentName: eurekaserver-deployment
deploymentLabel: eurekaserver

replicaCount: 1

image:
  repository: vishvanaths/eurekaserver
  tag: latest

containerPort: 8070

service:
  type: LoadBalancer
  port: 8070
  targetPort: 8070

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true